MILESTONE_TEMPLATE = [
    "TRANSPORT_ORDER_CREATED",
    "ASN_CREATED",
    "BOOKING_CONFIRMED",
    "PICKUP_COMPLETED",
    "IN_TRANSIT",
    "GATE_ARRIVAL",
    "DOCK_CHECKIN",
    "UNLOAD_COMPLETE",
    "GOODS_RECEIPT_CONFIRMED",
]

MILESTONE_SLA_HOURS = {
    "ASN_CREATED": 4,
    "BOOKING_CONFIRMED": 2,
    "PICKUP_COMPLETED": 2,
    "IN_TRANSIT": 6,
    "GATE_ARRIVAL": 12,
    "DOCK_CHECKIN": 1,
    "UNLOAD_COMPLETE": 2,
    "GOODS_RECEIPT_CONFIRMED": 4,
}

CRITICALITY_WEIGHT = {
    "JIT": 3,
    "JIS": 3,
    "STANDARD": 1,
    "LOW": 0.5,
}
